/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-05-25 01:00:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pagina_002dlogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/Pastas/apache-tomcat-9.0.45/webapps/startool/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1621904048000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t    <meta charset=\"UTF-8\">\r\n");
      out.write("\t    <meta name=\"viewport\" content=\"width=device-width, \r\n");
      out.write("\t    initial-scale=1.0\">\r\n");
      out.write("\t    <link rel=\"sortcut icon\" href=\"assets/img/logo-nav.png\" type=\"image/startool-companie\" />\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\" integrity=\"sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==\" crossorigin=\"anonymous\" />\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"assets/fonts/fonts/lineicons/font-css/LineIcons.css\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"assets/css/LineIcons.2.0.css\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"assets/css/bootstrap-5.0.0-alpha-2.min.css\">\r\n");
      out.write("\t\t<title>LOGIN | STARTOOL</title>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\tinput:focus{\r\n");
      out.write("\t\t\t\tbox-shadow: 0 0 0 0;\r\n");
      out.write("\t\t\t\tborder: 0 none;\r\n");
      out.write("\t\t\t\toutline: 0;\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body style=\"background-color: #323232;\">\r\n");
      out.write("\t    <section>\r\n");
      out.write("\t        <div>\r\n");
      out.write("\t            <center>\r\n");
      out.write("\t\t            <a href=\"/startool/entrada?acao=ListarStartups\">\r\n");
      out.write("\t\t            \t<img src=\"assets/img/logo.png\" alt=\"\" width=\"260\" height=\"340\" style=\"margin-top: 25px;\">\r\n");
      out.write("\t\t            </a>\r\n");
      out.write("\t\t            <p style=\"font-size: 25px; color: #c4c4c4;\">Faça Login para iniciar sua sessão</p>\r\n");
      out.write("\t\t            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LinkServletLogin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" method=\"post\">\r\n");
      out.write("\t\t\t            <div class=\"input-login-email\">\r\n");
      out.write("\t\t\t                <input type=\"text\" placeholder=\"Usuário ou RA\" class=\"input-login-user\" name=\"ra\">\r\n");
      out.write("\t\t\t                <img src=\"assets/img/icon/mail.png\" alt=\"\" width=\"35\">\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t            <div class=\"input-login-pass\">\r\n");
      out.write("\t\t\t                <input type=\"password\" placeholder=\"Senha\" class=\"input-login-user\" name=\"senha\">\r\n");
      out.write("\t\t\t                <img src=\"assets/img/icon/lock.png\" alt=\"\" width=\"35\">\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t            \t\t<input type=\"hidden\" name=\"acao\" value=\"ValidarLogin\">\r\n");
      out.write("\t\t\t            <div class=\"container\" style=\"margin-top: 45px;\">\r\n");
      out.write("\t\t\t                \r\n");
      out.write("\t\t\t                <div class=\"row\">\r\n");
      out.write("\t\t\t                    <div class=\"col-md-3\"></div>\r\n");
      out.write("\t\t\t                     <div class=\"col-md-3\">\r\n");
      out.write("\t\t\t                    </div>\r\n");
      out.write("\t\t\t                    <div class=\"col-md-3\">\r\n");
      out.write("\t\t\t                    \t<input type=\"submit\" class=\"button-to-log\" title=\"Entrar\">\r\n");
      out.write("\t\t\t                    </div>\r\n");
      out.write("\t\t\t                    <div class=\"col-md-3\"></div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t            <input type=\"hidden\" name=\"acao\" value=\"ValidarLogin\">\r\n");
      out.write("\t\t            </form>\r\n");
      out.write("\t\t            <div style=\"margin-top: 65px;\">\r\n");
      out.write("\t\t                <p style=\"font-size: 25px; color: #c4c4c4;\">Ainda não tem conta? <a href=\"/startool/entrada?acao=PaginaCadastrar\" class=\"link-sign-up-login entrar_button\">Cadastre-se</a></p>\r\n");
      out.write("\t\t            </div>\t            \r\n");
      out.write("\t            </center>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </section>\r\n");
      out.write("\t\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /pagina-login.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/acesso");
      // /pagina-login.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("LinkServletLogin");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
